# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'uchoa'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
normalize_data: False
checkpoint_load_path: models/DPDP/DPDP/logs/${problem}_${coords_dist}100/best_val_loss_checkpoint.tar
heatmap_load_path: models/DPDP/DPDP/results/${problem}/${problem}_${coords_dist}100_val_seed4321/heatmaps/heatmaps_${problem}_${coords_dist}100.pkl


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: uchoa
    # if None in the following two args, then all are mixed
    depot_type: E # Depot Position (uchoa only): C = central (500, 500), E = eccentric (0, 0), R = random
    customer_type:  # Customer Position (uchoa only): C = Clustered, RC = Random-Clustered (half half), R = Random
    demand_type:   # if None demand will be generated uniformly at random
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
  sampling_args:
    sample_size: 4 # 512
    graph_size: ${graph_size}
    k: 16
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)

# demand distribution choices:
        # 0 = unitary (1)
        # 1 = small values, large variance (1-10)
        # 2 = small values, small variance (5-10)
        # 3 = large values, large variance (1-100)
        # 4 = large values, large variance (50-100)
        # 5 = depending on quadrant top left and bottom right (even quadrants) (1-50), others (51-100) so add 50
        # 6 = many small, few large most (70 to 95 %, unclear so take uniform) from (1-10), rest from (50-100)