name: l2o
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py38heb32a55_1
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py38hd667e15_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.8=py38ha5dfef3_0
  - cuda91=1.0=h4c16780_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.4.4=h295c915_0
  - fastprogress=1.0.3=py_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.2=py38_1
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.8.2=py38h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - libllvm11=11.1.0=h3826bc1_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.19.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h1abd341_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numexpr=2.8.1=py38h6abb31d_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - overpy=0.6=pyhd8ed1ab_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py38h295c915_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py38h06a4308_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h578d9bd_4
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-louvain=0.15=pyhd3deb0d_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.26.0=pyhd8ed1ab_1
  - routingpy=0.3.3=pyhd8ed1ab_0
  - scipy=1.7.1=py38h292c36d_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.37.2=hc218d9a_0
  - tensorboardx=2.5.1=pyhd8ed1ab_0
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - time=1.8=h516909a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.12.1=py38_cu113
  - torchvision=0.13.1=py38_cu113
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.14.1
    - accelerate==0.13.1
    - antlr4-python3-runtime==4.8
    - anyio==3.6.2
    - asttokens==2.0.8
    - atari-py==0.2.9
    - beautifulsoup4==4.11.1
    - charset-normalizer==2.0.6
    - cloudpickle==1.6.0
    - cupy-cuda113==10.6.0
    - cycler==0.10.0
    - deprecated==1.2.13
    - dill==0.3.4
    - executing==1.1.1
    - fastrlock==0.8
    - filelock==3.8.0
    - gdown==4.5.1
    - google-auth==1.35.0
    - grpcio==1.41.0
    - gym==0.26.2
    - gym-notices==0.0.8
    - hydra-core==1.1.1
    - hygese==0.0.0.8
    - idna==3.2
    - importlib-resources==5.2.2
    - ipykernel==6.16.2
    - ipython==8.5.0
    - ipywidgets==8.0.2
    - isodate==0.6.0
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyter-server==1.21.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.3.2
    - llvmlite==0.38.1
    - lxml==4.9.1
    - markdown==3.3.4
    - matplotlib==3.4.3
    - mistune==2.0.4
    - nbclassic==0.4.5
    - nbconvert==7.2.2
    - nbformat==5.7.0
    - notebook==6.5.1
    - notebook-shim==0.2.0
    - nuitka==0.7.5
    - numba==0.55.2
    - numpy==1.20.3
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.3.56
    - pillow==9.2.0
    - protobuf==3.18.1
    - psutil==5.8.0
    - pure-eval==0.2.2
    - pybind11==2.8.1
    - pybind11-global==2.8.1
    - pygments==2.13.0
    - pyllist==0.3
    - pyrfr==0.8.2
    - pyyaml==6.0
    - qtconsole==5.3.2
    - qtpy==2.2.1
    - rdflib==6.0.1
    - rsa==4.7.2
    - scikit-learn==1.1.2
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stable-baselines3==1.2.0
    - stack-data==0.5.1
    - tabulate==0.8.10
    - tensorboard==2.10.1
    - tensorboard-logger==0.1.0
    - tianshou==0.4.3
    - tinycss2==1.2.1
    - torch-cluster==1.6.0
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - torch-spline-conv==1.2.1
    - tsplib95==0.7.1
    - verypy==0.5.1
    - websocket-client==1.4.1
    - widgetsnbextension==4.0.3
    - wrapt==1.14.1
prefix: /home/thyssens/anaconda3/envs/l2o
