# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'uchoa'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: # data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
normalize_data: True
checkpoint_load_path: models/DACT/DACT/pretrained/cvrp100-epoch-198.pt


# demand distribution choices:
        # 0 = unitary (1)
        # 1 = small values, large variance (1-10)
        # 2 = small values, small variance (5-10)
        # 3 = large values, large variance (1-100)
        # 4 = large values, large variance (50-100)
        # 5 = depending on quadrant top left and bottom right (even quadrants) (1-50), others (51-100) so add 50
        # 6 = many small, few large most (70 to 95 %, unclear so take uniform) from (1-10), rest from (50-100)

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: uchoa
    single_large_instance: data/train_data/${problem}_10000/${coords_dist}_${env_kwargs.generator_args.depot_type}_${env_kwargs.generator_args.customer_type}_${env_kwargs.generator_args.demand_type}/single_large_instance.pt
    # if None in the following two args, then all are mixed
    depot_type: R # Depot Position (uchoa only): C = central (500, 500), E = eccentric (0, 0), R = random
    customer_type: RC # Customer Position (uchoa only): C = Clustered, RC = Random-Clustered (half half), R = Random
    demand_type: 0  # if None demand will be a mixture of above demand distributions
    normalize_demands: True  # if None or False - demands will remain un-normalized (not between 0-1)
  sampling_args:
    sample_size: 512
    graph_size: ${graph_size}
    subsample: True
    k: 16
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)